config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  post '/comments', to: 'comments#create'

  resources :projects
  
  devise_for :users, path: '', 
              path_names: { 
                sign_in: 'login', 
                sign_up: 'register', 
                sign_out: 'logout', 
                edit: 'profile' 
              },
              controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_rich_text :description

  enum status: {Created: 0, Started: 1, Stopped: 2, Completed: 3}
  enum display: {Private: 0, Public: 1}

  validates :name, presence: :true, length: { 
    maximum: 200,
    minimum: 5,
    message: " should be between 5 to 200 characters"
  }, on: :update, on: :create
  
  validates :estimated_effort, numericality: { 
    only_integer: true, 
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 10,
    message: " must be at least 1 and not greater than 10"
  }
  validates :actual_effort, numericality: { 
    only_integer: true, 
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 10,
    message: " must be at least 1 and not greater than 10"
  }, on: :update

  validates :description, presence: :true, length: { 
    maximum: 2000,
    minimum: 50, 
    message: " should be meaningful"
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
  
  has_many :projects

  validates :full_name, presence: :true, length: { 
    maximum: 50,
    minimum: 2,
    message: " must be between 2 to 50 characters."
  }, on: :update, on: :create

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.full_name = auth.info.name
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0, 20]
        # issues below
        # user.provider = auth.provider

        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        # user.skip_confirmation!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :location, :about, :status])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_valid_project

  def create
    project = Project.find(comment_params[:project_id])

    if comment_params[:content].blank?
      return render json: {success: false}     
    end

    @comment = Comment.new(
      user_id: current_user.id,
      project_id: project.id,
      content: comment_params[:content],
    )

    if @comment.save
      CommentChannel.broadcast_to project, message: render_comment(@comment)
      return render json: {success: true}
    else  
      return render json: {success: false}
    end
  end
  


  private
    def render_comment(comment)
      self.render_to_string partial: 'projects/comment', locals: {comment: comment}
    end
    def comment_params
      params.require(:comment).permit(:content, :project_id)
    end
    def is_valid_project
      redirect_to dashboard_path, alert: 'Invalid project' unless Project.find(comment_params[:project_id]).present?
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.all.where(display: 'Public')
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :set_project, except: [:new, :create]
  before_action :is_authorised, only: [:edit, :update]

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to root_path, notice: "Project created successfully."
    else
      redirect_to request.referrer, flash: { error: @project.errors.full_messages }
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      if !(@project.actual_effort > 0) && project_params[:status] == "Completed"
        return redirect_to request.referrer, flash: {error: "In order to mark your project compled, you need to add the Actual Effort from 1 to 10"}
      else
      redirect_to edit_project_path(@project), notice: "Your project has been updated successfully!"
      end
    else
      return redirect_to request.referrer, flash: {error: @project.errors.full_messages}
    end
  end

  def show
    @project = Project.find(params[:id])
    @comments = Comment.where(project_id: params[:id])
  end

  def status_complete
		@project = Project.find(params[:id])

		if @project.status != 3
			if @project.status == 3
				flash[:notice] = "Saved..."
			else
				flash[:alert] = "Something went wrong..."
			end

			redirect_to request.referrer
		end
	end

  private

    def set_project
      @project = Project.find(params[:id])
    end
    # If current user is the owner of the project, then permissions given to run update & create
    def is_authorised
      redirect_to root_path, alert: "Hmm...Sorry, but you don't have permission to do this." unless current_user.id == @project.user_id
    end

    def project_params
      params.require(:project).permit(:estimated_effort, :actual_effort, :display, :name, :status, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def avatar_url(user)
    if user.image?
      user.image
    else
      'avatar.png'
    end
  end

  def project_status(status)
    case status
    when 'Created'
      'is-danger'
    when 'Started'
      'is-info'
    when 'Stopped'
      'is-warning'
    else 
      'is-success'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeImprovements</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  </head>

  <body>
    <% unless current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/notices' %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<section class="hero is-white">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-12-tablet is-9-desktop is-9-widescreen">
          <% @projects.each do |project| %>
            <div class="form-layout mb-5">
                <div class="form-outer">
                  <div class="form-header">
                    <div class="form-header-inner">
                      <div class="left">
                        <%= link_to edit_project_path(project) do %>
                          <h2 class="title is-4"><%= project.name.titleize %></h2>
                        <% end %>
                        
                      </div>
                      <div class="right">
                        <div class="buttons">
                          <%= link_to "View Comments", project_path(project), class: "button is-primary is-small" %>
                        
                          <%= link_to project.status.humanize, 
                                              edit_project_path(project), 
                                              class: "button is-outlined is-small #{project_status(project.status)}" %>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="box is-shadowless">
                    <div class="columns mt-5 mb-4">
                      <div class="column is-7 pt-0">
                        <div class="card is-shadowless">
                          <header class="card-header is-shadowless p-1">
                            <span class="icon"><i class="fas fa-user"></i></span>
                            <p class="card-header-title p-0">
                            <%= project.user.full_name %> | <span class="icon"><i class="far fa-clock"></i></span> <%= project.created_at.strftime('%d, %b %Y')%>
                            </p>
                          </header>
                          <div class="card-content p-1">
                            <div class="content">
                              <%= project.description %>
                            </div>
                          </div>
                          
                        </div>
                      </div>
                      <div class="columns is-mobile p-2">
                        <div class="column">
                          <div class="box effort-box">
                            <p>Estimated level of effort</p>
                            <p class="effort-num">
                              <%= project.estimated_effort %>
                            </p>
                          </div>
                        </div>
                        <div class="column">
                          <div class="box effort-box">
                            <p>Actual level<br /> of effort</p>
                              <p class="effort-num has-text-success">
                                <% unless project.status != 'Completed' %>
                                  <%= project.estimated_effort %>
                                <% end %>
                              </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/projects/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <%= image_tag avatar_url(comment.user), class: 'is-rounded'%>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.full_name %></strong>
          <br>
          <%= comment.content %>
        </p>
      </div>
      <nav class="level is-mobile">
        <div class="level-left">
          <div class="level-item">
            <small><%= time_ago_in_words(comment.created_at) %></small>
          </div>
        </div>
      </nav>
    </div>
  </article>
</div>

app/views/projects/edit.html.erb
<section class="hero is-white is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-9-tablet is-9-desktop is-9-widescreen">
          <h2 class="title has-text-centered">Edit Project</h2>
          <%= form_for @project do |f| %>
            <div class="field">
              <label class="label">Update Project</label>
              <div class="select is-info">
                <%= f.select :status, Project.statuses.map {|key, value| [key.humanize, key]}, selected: @project.status %>
              </div>
            </div>
            <hr>
            <div class="field">
              <label class="label">Project Name</label>
              <div class="control">
                <%= f.text_field :name, autocomplete: 'name', placeholder: @project.name, class: 'input is-info' %>
              </div>
            </div>

            <div class="columns is-multiline is-mobile">
              <div class="column is-one-third">
                <div class="field">
                  <label class="label">Estimated Effort</label>
                  <div class="control">
                    <%= f.number_field :estimated_effort, autocomplete: 'name', placeholder: @project.estimated_effort, class: 'input is-info' %>
                  </div>
                </div>
              </div>
              <div class="column is-one-third">
                <div class="field">
                  <label class="label">Actual Effort</label>
                  <div class="control">
                    <%= f.number_field :actual_effort, autocomplete: 'name', placeholder: 'actual effort', class: 'input is-info' %>
                  </div>
                </div>
              </div>
              
              <div class="column is-one-third">
                <div class="field">
                  <label class="label">Private / Public</label>
                  <div class="control">
                    <div class="select is-info">
                      <%= f.select :display, Project.displays.map {|key, value| [key.humanize, key]}, selected: @project.display %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="field">
              <label class="label">Description</label>
              <div class="control">
                <%= f.rich_text_area :description, id: "rich-editor", autocomplete: 'description', placeholder: @project.description, class: 'textarea is-info', rows: 50, cols: 5 %>
              </div>
            </div>


            <div class="field is-grouped">
              <div class="control">
                <%= f.submit "Update Project", class: "button is-link" %>
              </div>
              <div class="control">
                <%= link_to "Cancel", root_path, class: "button is-link is-light" %>
              </div>
            </div>

          <% end %>
         
        </div>
      </div>
    </div>
  </div>
</section>

app/views/projects/new.html.erb
<section class="hero is-white is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-8-tablet is-7-desktop is-6-widescreen">
          <h2 class="title has-text-centered">Create a Project</h2>

          <%= form_for @project do |f| %>
          
          <div class="field">
            <label class="label">Project Name</label>
            <div class="control">
              <%= f.text_field :name, autocomplete: 'name', placeholder: 'Project Name', class: 'input is-info' %>
            </div>
          </div>

          <div class="columns is-multiline is-mobile">
            <div class="column is-two-thirds">
              <div class="field">
                <label class="label">Estimated Level of Effort</label>
                <div class="control">
                  <%= f.number_field :estimated_effort, autocomplete: 'name', placeholder: 'Between 1 to 10', class: 'input is-info' %>
                </div>
              </div>
            </div>
            <div class="column is-one-third">
              <div class="field">
                <label class="label">Private / Public</label>
                <div class="control">
                  <div class="select is-info">
                    <%= f.select :display, Project.displays.map {|key, value| [key.humanize, key]}, selected: 'Public' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <div class="field">
            <label class="label">Description</label>
            <div class="control">
              <%= f.rich_text_area :description, id: "rich-editor", autocomplete: 'description', placeholder: 'Briefly describe the scope of project', class: 'textarea is-info', rows: 50, cols: 5 %>
            </div>
          </div>

          <div class="field is-grouped">
            <div class="control">
              <%= f.submit "Create Project", class: "button is-link" %>
            </div>
            <div class="control">
              <%= link_to "Cancel", root_path, class: "button is-link is-light" %>
            </div>
          </div>

          <% end %>
         
        </div>
      </div>
    </div>
  </div>
</section>

app/views/projects/show.html.erb
<section class="section" data-channel-subscribe="project" data-project-id="<%= @project.id %>">
  <div class="container">
    <div class="columns">
      <div class="column">
        <article class="panel is-success is-light">
          <p class="panel-heading">
            <%= @project.name %>
          </p>
          
          
          <a class="panel-block">
            <strong>Project Owner:</strong> <%= @project.user.full_name %>
          </a>
          <a class="panel-block">
            <strong>Project ID:</strong> <%= @project.id %>
          </a>
          <a class="panel-block">
            <strong>Estimated Effort:</strong> <%= @project.estimated_effort %>
          </a>
          <a class="panel-block">
            <strong>Created On:</strong> <%= @project.created_at.strftime('%d, %b %Y') %>
          </a>
        </article>
      </div>
      <div class="column is-two-thirds">
        <p class="menu-label">
          Project Comments
        </p>
        <hr>
        <div id="comment-list">
          <% @comments.each do |c| %>
            <%= render 'comment', comment: c %>
          <% end %>
        </div>
        <hr>
        <article class="media">
          <figure class="media-left image is-64x64 mr-2">
            <%= image_tag avatar_url(current_user), class: 'is-rounded'%>
          </figure>
          <div class="media-content">
            <%= form_with model: Comment.new, id: "new-comment" do |f| %>
              <%= f.hidden_field :project_id, value: @project.id %>
              <div class="field">
                <%= f.text_area :content, class: 'textarea', placeholder: "Make a comment..." %>
              </div>
              <div class="field is-pulled-right">
                <%= f.submit "Post Comment", class: 'button is-primary' %>                          
              </div>
            <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar is-white has-shadow">
  <div class="navbar-brand">
    <%= link_to root_path, class: 'navbar-item' do %>
      <%= image_tag 'homeImprovements.png', width: "40", height: "37" %>
    <% end %>
    <div class="navbar-burger" data-target="navMenuColorlink-example">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navMenuColorlink-example" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Home', root_path, class: 'navbar-item' %>
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to 'New Project', new_project_path, class: "button is-success is-small capitalize" %>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <% if (!user_signed_in?) %>
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'Login', new_user_session_path, class: "button is-primary is-light" %>
            </p>
            <p class="control">
              <%= link_to 'Register', new_user_registration_path, class: "button is-primary is-light" %>
            </p>
          </div>
        <% else %>
          <div class="navbar-item has-dropdown is-hoverable">
            
            <a href="" class="navbar-item">
              <figure class="image is-32x32 mr-2">
                <%= image_tag avatar_url(current_user), class: 'is-rounded'%>
              </figure>
              <%= current_user.full_name %>
              
            </a>

            <div class="navbar-dropdown">
              <%= link_to 'Profile', edit_user_registration_path, class: "navbar-item" %>
              <a class="navbar-item" href="#">
                Dashboard
              </a>
              <hr class="navbar-divider">
              <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "navbar-item" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<script>
document.addEventListener('DOMContentLoaded', () => {

  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  if ($navbarBurgers.length > 0) {
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {
        const target = el.dataset.target;
        const $target = document.getElementById(target);
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');
      });
    });
  }

});
</script>

app/views/shared/_notices.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% i = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      new Noty({
          type: '<%= i %>',
          layout: 'bottomLeft',
          timeout: '5000',
          text: '<%= value %>',
          theme: 'semanticui'
      }).show();
    <% end %>
  </script>
<% end %>